server:
  port: 8088

spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:securitydb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.sql: debug
#    org.hibernate.type: trace2